from django.urls import path

from .views import (
    AgentChatView,
    ApprovalRequestDetailView,
    ApprovalRequestListView,
    AuthLoginView,
    AuthMeView,
    AuthRegisterView,
    BlogAboutView,
    BlogAgentChatView,
    BlogArchiveView,
    BlogArticleDetailView,
    BlogArticleListCreateView,
    BlogArticlePublishView,
    BlogCategoryListView,
    BlogCommentCreateView,
    BlogImageUploadView,
    BlogTagListView,
    ConversationDetailView,
    ConversationListView,
    DocumentDetailView,
    DocumentListUploadView,
    DocumentReindexView,
    EvaluationCaseListView,
    EvaluationRunView,
    KnowledgeBaseDetailView,
    KnowledgeBaseListView,
    KnowledgeSearchView,
    MCPToolDetailView,
    MCPToolExecuteView,
    MCPToolListView,
    ObservabilityDashboardView,
    SecurityAuditListView,
    SecurityStatusView,
)

urlpatterns = [
    path("auth/login/", AuthLoginView.as_view(), name="auth-login"),
    path("auth/register/", AuthRegisterView.as_view(), name="auth-register"),
    path("auth/me/", AuthMeView.as_view(), name="auth-me"),
    path("security/status/", SecurityStatusView.as_view(), name="security-status"),
    path("security/audit-events/", SecurityAuditListView.as_view(), name="security-audit-events"),
    path("chat/", AgentChatView.as_view(), name="agent-chat"),
    path("approvals/", ApprovalRequestListView.as_view(), name="approval-list"),
    path("approvals/<int:pk>/", ApprovalRequestDetailView.as_view(), name="approval-detail"),
    path("mcp-tools/", MCPToolListView.as_view(), name="mcp-tool-list"),
    path("mcp-tools/<int:pk>/", MCPToolDetailView.as_view(), name="mcp-tool-detail"),
    path("mcp-tools/<int:pk>/execute/", MCPToolExecuteView.as_view(), name="mcp-tool-execute"),
    path("observability/", ObservabilityDashboardView.as_view(), name="observability-dashboard"),
    path("evaluation-cases/", EvaluationCaseListView.as_view(), name="evaluation-case-list"),
    path("evaluation-runs/", EvaluationRunView.as_view(), name="evaluation-run"),
    path("conversations/", ConversationListView.as_view(), name="conversation-list"),
    path("conversations/<int:pk>/", ConversationDetailView.as_view(), name="conversation-detail"),
    path("knowledge-bases/", KnowledgeBaseListView.as_view(), name="knowledge-base-list"),
    path("knowledge-bases/<int:pk>/", KnowledgeBaseDetailView.as_view(), name="knowledge-base-detail"),
    path("documents/", DocumentListUploadView.as_view(), name="document-list-upload"),
    path("documents/<int:pk>/", DocumentDetailView.as_view(), name="document-detail"),
    path("documents/<int:pk>/reindex/", DocumentReindexView.as_view(), name="document-reindex"),
    path("knowledge-search/", KnowledgeSearchView.as_view(), name="knowledge-search"),
    path("blog/articles/", BlogArticleListCreateView.as_view(), name="blog-article-list-create"),
    path("blog/articles/<str:slug>/", BlogArticleDetailView.as_view(), name="blog-article-detail"),
    path("blog/articles/<str:slug>/publish/", BlogArticlePublishView.as_view(), name="blog-article-publish"),
    path("blog/articles/<str:slug>/comments/", BlogCommentCreateView.as_view(), name="blog-comment-create"),
    path("blog/images/", BlogImageUploadView.as_view(), name="blog-image-upload"),
    path("blog/categories/", BlogCategoryListView.as_view(), name="blog-category-list"),
    path("blog/tags/", BlogTagListView.as_view(), name="blog-tag-list"),
    path("blog/archive/", BlogArchiveView.as_view(), name="blog-archive"),
    path("blog/about/", BlogAboutView.as_view(), name="blog-about"),
    path("blog/agent/chat/", BlogAgentChatView.as_view(), name="blog-agent-chat"),
]
