from django.urls import path

from .views import (
    AgentChatView,
    BlogAboutView,
    BlogAgentChatView,
    BlogArchiveView,
    BlogArticleDetailView,
    BlogArticleListCreateView,
    BlogArticlePublishView,
    BlogCategoryListView,
    BlogCommentCreateView,
    BlogImageUploadView,
    BlogTagListView,
    ConversationDetailView,
    ConversationListView,
    DocumentListUploadView,
    DocumentReindexView,
    KnowledgeBaseListView,
    KnowledgeSearchView,
)

urlpatterns = [
    path("chat/", AgentChatView.as_view(), name="agent-chat"),
    path("conversations/", ConversationListView.as_view(), name="conversation-list"),
    path("conversations/<int:pk>/", ConversationDetailView.as_view(), name="conversation-detail"),
    path("knowledge-bases/", KnowledgeBaseListView.as_view(), name="knowledge-base-list"),
    path("documents/", DocumentListUploadView.as_view(), name="document-list-upload"),
    path("documents/<int:pk>/reindex/", DocumentReindexView.as_view(), name="document-reindex"),
    path("knowledge-search/", KnowledgeSearchView.as_view(), name="knowledge-search"),
    path("blog/articles/", BlogArticleListCreateView.as_view(), name="blog-article-list-create"),
    path("blog/articles/<str:slug>/", BlogArticleDetailView.as_view(), name="blog-article-detail"),
    path("blog/articles/<str:slug>/publish/", BlogArticlePublishView.as_view(), name="blog-article-publish"),
    path("blog/articles/<str:slug>/comments/", BlogCommentCreateView.as_view(), name="blog-comment-create"),
    path("blog/images/", BlogImageUploadView.as_view(), name="blog-image-upload"),
    path("blog/categories/", BlogCategoryListView.as_view(), name="blog-category-list"),
    path("blog/tags/", BlogTagListView.as_view(), name="blog-tag-list"),
    path("blog/archive/", BlogArchiveView.as_view(), name="blog-archive"),
    path("blog/about/", BlogAboutView.as_view(), name="blog-about"),
    path("blog/agent/chat/", BlogAgentChatView.as_view(), name="blog-agent-chat"),
]
