import type { BlogTheme } from './themeTypes';

export const presetThemes: BlogTheme[] = [
  {
    id: 'default',
    name: '默认',
    description: '深海蓝铜配色，简洁专业',
    bgColor: '#ffffff',
    textColor: '#182329',
    headingColor: '#182329',
    linkColor: '#276678',
    codeBg: '#1a2332',
    codeText: '#e0e8ec',
    blockquoteBg: '#f4f6f7',
    blockquoteBorder: '#276678',
    borderColor: '#dce3e6',
    fontFamily: 'Inter, "PingFang SC", "Microsoft YaHei", "Noto Sans SC", sans-serif',
    headingFont: 'Inter, "PingFang SC", "Microsoft YaHei", "Noto Sans SC", sans-serif',
    fontSize: '15px',
    lineHeight: '1.8',
    contentWidth: '800px',
    paragraphSpacing: '16px',
    headingSpacing: '24px',
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'GitHub 风格，清新明亮',
    bgColor: '#ffffff',
    textColor: '#24292e',
    headingColor: '#24292e',
    linkColor: '#0366d6',
    codeBg: '#f6f8fa',
    codeText: '#24292e',
    blockquoteBg: '#f6f8fa',
    blockquoteBorder: '#dfe2e5',
    borderColor: '#e1e4e8',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
    headingFont: '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
    fontSize: '16px',
    lineHeight: '1.6',
    contentWidth: '860px',
    paragraphSpacing: '16px',
    headingSpacing: '24px',
  },
  {
    id: 'newsprint',
    name: '新闻纸',
    description: '温暖复古，报纸排版风格',
    bgColor: '#f8f5ec',
    textColor: '#2c2c2c',
    headingColor: '#1a1a1a',
    linkColor: '#8b4513',
    codeBg: '#ede8d8',
    codeText: '#2c2c2c',
    blockquoteBg: '#f0ead6',
    blockquoteBorder: '#8b7355',
    borderColor: '#d4cbb8',
    fontFamily: 'Georgia, "Noto Serif SC", "Songti SC", "SimSun", serif',
    headingFont: 'Georgia, "Noto Serif SC", "Songti SC", "SimSun", serif',
    fontSize: '16px',
    lineHeight: '1.9',
    contentWidth: '720px',
    paragraphSpacing: '20px',
    headingSpacing: '32px',
  },
  {
    id: 'academic',
    name: '学术',
    description: '正式学术风格，清晰结构',
    bgColor: '#ffffff',
    textColor: '#333333',
    headingColor: '#1a1a2e',
    linkColor: '#2c5282',
    codeBg: '#f0f4f8',
    codeText: '#2d3748',
    blockquoteBg: '#ebf8ff',
    blockquoteBorder: '#2c5282',
    borderColor: '#e2e8f0',
    fontFamily: '"Times New Roman", "Noto Serif SC", "Songti SC", serif',
    headingFont: 'Georgia, "Noto Serif SC", serif',
    fontSize: '15px',
    lineHeight: '1.8',
    contentWidth: '760px',
    paragraphSpacing: '14px',
    headingSpacing: '28px',
  },
  {
    id: 'dark',
    name: '暗夜',
    description: '深色主题，护眼舒适',
    bgColor: '#1e1e1e',
    textColor: '#d4d4d4',
    headingColor: '#e0e0e0',
    linkColor: '#569cd6',
    codeBg: '#2d2d2d',
    codeText: '#d4d4d4',
    blockquoteBg: '#252525',
    blockquoteBorder: '#569cd6',
    borderColor: '#3e3e3e',
    fontFamily: 'Inter, "PingFang SC", "Microsoft YaHei", "Noto Sans SC", sans-serif',
    headingFont: 'Inter, "PingFang SC", "Microsoft YaHei", "Noto Sans SC", sans-serif',
    fontSize: '15px',
    lineHeight: '1.8',
    contentWidth: '800px',
    paragraphSpacing: '16px',
    headingSpacing: '24px',
  },
  {
    id: 'forest',
    name: '墨绿',
    description: '自然森林色调，清新雅致',
    bgColor: '#f5f7f0',
    textColor: '#2d3b2d',
    headingColor: '#1a2e1a',
    linkColor: '#3a7d44',
    codeBg: '#e8ede5',
    codeText: '#2d3b2d',
    blockquoteBg: '#eef2e8',
    blockquoteBorder: '#6b8f5e',
    borderColor: '#c8d4bc',
    fontFamily: '"Noto Serif SC", Georgia, "Songti SC", serif',
    headingFont: '"Noto Sans SC", "PingFang SC", "Microsoft YaHei", sans-serif',
    fontSize: '15px',
    lineHeight: '1.85',
    contentWidth: '780px',
    paragraphSpacing: '16px',
    headingSpacing: '26px',
  },
  {
    id: 'ocean',
    name: '海洋',
    description: '深蓝色调，宁静深邃',
    bgColor: '#f0f5fa',
    textColor: '#1a2a3a',
    headingColor: '#0d1b2a',
    linkColor: '#1b6ca8',
    codeBg: '#dce8f0',
    codeText: '#1a2a3a',
    blockquoteBg: '#e4eef6',
    blockquoteBorder: '#1b6ca8',
    borderColor: '#c0d4e4',
    fontFamily: '"PingFang SC", "Microsoft YaHei", "Noto Sans SC", sans-serif',
    headingFont: '"PingFang SC", "Microsoft YaHei", "Noto Sans SC", sans-serif',
    fontSize: '15px',
    lineHeight: '1.8',
    contentWidth: '800px',
    paragraphSpacing: '16px',
    headingSpacing: '24px',
  },
  {
    id: 'lavender',
    name: '薰衣草',
    description: '淡紫色调，优雅浪漫',
    bgColor: '#faf8fc',
    textColor: '#2d2640',
    headingColor: '#1e1633',
    linkColor: '#6b4fa0',
    codeBg: '#ede8f5',
    codeText: '#2d2640',
    blockquoteBg: '#f3eef9',
    blockquoteBorder: '#9b7fc7',
    borderColor: '#d8cfe8',
    fontFamily: '"Noto Sans SC", "PingFang SC", "Microsoft YaHei", sans-serif',
    headingFont: '"Noto Serif SC", Georgia, "Songti SC", serif',
    fontSize: '15px',
    lineHeight: '1.8',
    contentWidth: '780px',
    paragraphSpacing: '16px',
    headingSpacing: '24px',
  },
];

export function getThemeById(id: string): BlogTheme | undefined {
  return presetThemes.find(t => t.id === id);
}

export function createEmptyTheme(): BlogTheme {
  return {
    id: `custom-${Date.now()}`,
    name: '自定义主题',
    description: '我的自定义主题',
    bgColor: '#ffffff',
    textColor: '#333333',
    headingColor: '#1a1a1a',
    linkColor: '#276678',
    codeBg: '#f5f5f5',
    codeText: '#333333',
    blockquoteBg: '#f9f9f9',
    blockquoteBorder: '#276678',
    borderColor: '#e0e0e0',
    fontFamily: 'Inter, "PingFang SC", "Microsoft YaHei", "Noto Sans SC", sans-serif',
    headingFont: 'Inter, "PingFang SC", "Microsoft YaHei", "Noto Sans SC", sans-serif',
    fontSize: '15px',
    lineHeight: '1.8',
    contentWidth: '800px',
    paragraphSpacing: '16px',
    headingSpacing: '24px',
  };
}