# Generated by Django 5.2.16 on 2026-09-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_api", "0021_blogarticle_author_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticle",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
