# Generated by Django 4.2 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0024_mcp_tool_stats_and_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='category',
            field=models.CharField(
                choices=[
                    ('tech_docs', '技术文档'),
                    ('product_docs', '产品文档'),
                    ('learning_notes', '学习笔记'),
                    ('project_docs', '项目资料'),
                    ('other', '其他'),
                ],
                default='other',
                help_text='知识库分类',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="标签列表，如 ['AI', 'Python', '教程']"),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='是否已归档'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='排序顺序，数字越小越靠前'),
        ),
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['sort_order', 'name']},
        ),
    ]