# Generated by Django 5.2.16 on 2026-09-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_api", "0025_knowledge_base_category_archive_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticle",
            name="cover_image",
            field=models.TextField(blank=True, default=""),
        ),
    ]
